async function renderEditor(mapId){
  const map=await idbGet('maps',mapId);if(!map)return;const project=await idbGet('projects',map.projectId);state.screen='editor';state.projectId=map.projectId;state.mapId=map.id
  $app.innerHTML=`<div class="editor"><header class="topbar"><div class="topbar-left"><button id="backProject" class="icon-btn">←</button><div class="brand"><span>TC</span></div><div class="title-stack"><small>${esc(project?.name||'Проект')}</small><input id="mapTitle" value="${esc(map.name)}"></div></div><div class="topbar-actions"><button id="undo" class="icon-btn" title="Undo">↶</button><button id="redo" class="icon-btn" title="Redo">↷</button><span class="divider"></span><button id="duplicate" class="icon-btn" title="Дублировать">⧉</button><button id="save" class="secondary">✓ Сохранить</button><button id="export" class="primary">⇩ Экспорт</button></div></header><main class="editor-layout"><aside class="toolbar" id="toolbar"></aside><div class="canvas-wrap"><canvas id="mapCanvas"></canvas><div class="canvas-hint">Колесо — масштаб · Alt/средняя кнопка — перемещение · Delete — удалить · двойной клик — текст</div></div><aside class="right-panel" id="rightPanel"></aside></main></div>`
  const editor=new MapEditor($('#mapCanvas'),map,async m=>{await idbPut('maps',deep(m));const p=await idbGet('projects',m.projectId);if(p){p.updatedAt=now();await idbPut('projects',p)}},sel=>$('#duplicate').disabled=!sel);state.editor=editor;$('#duplicate').disabled=true
  renderToolbar(editor,map);renderRightPanel(editor,map)
  $('#backProject').onclick=()=>{editor.dispose();renderProject(map.projectId)};$('#mapTitle').oninput=e=>{map.name=e.target.value;map.updatedAt=now();editor.scheduleSave()};$('#save').onclick=async()=>{await idbPut('maps',deep(map));toast('Карта сохранена')};$('#undo').onclick=()=>editor.undo();$('#redo').onclick=()=>editor.redo();$('#duplicate').onclick=()=>editor.duplicate();$('#export').onclick=()=>exportMapModal(editor,map)
}
function renderToolbar(editor,map){
  const tools=Object.entries(TOOL_LABELS).filter(([id])=>!TOOL_KINDS[id]||TOOL_KINDS[id].includes(map.kind));$('#toolbar').innerHTML=tools.map(([id,[icon,label]])=>`<button class="tool ${id==='select'?'active':''}" data-tool="${id}" title="${label}"><b style="font-size:18px;font-weight:500">${icon}</b><span>${label}</span></button>`).join('');$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');editor.setTool(b.dataset.tool)})
}
function renderRightPanel(editor,map){
  const rp=$('#rightPanel');rp.innerHTML=`<div class="map-chip">▦ ${KIND_LABELS[map.kind]}</div><section class="panel"><div class="panel-head"><div><span class="eyebrow">Структура</span><h3>Слои</h3></div><button id="addLayer" class="icon-btn" title="Добавить слой">＋</button></div><div class="layer-list">${map.layers.map(l=>layerRow(l,map.activeLayerId)).join('')}</div></section><section class="panel settings"><span class="eyebrow">Документ</span><h3>Карта</h3><div class="field-grid two"><label>Колонки<input id="cols" type="number" min="4" max="200" value="${map.settings.columns}"></label><label>Строки<input id="rows" type="number" min="4" max="200" value="${map.settings.rows}"></label></div><label class="field">Сетка<select id="gridType"><option value="square">Квадратная</option><option value="hex-flat">Hex flat</option><option value="hex-pointy">Hex pointy</option></select></label><label class="field">Размер клетки, px<input id="cellSize" type="number" min="20" max="120" value="${map.settings.cellSize}"></label><div class="toggle"><span>Показывать сетку</span><button id="gridVisible" class="switch ${map.settings.gridVisible?'on':''}"><span></span></button></div><div class="toggle"><span>Привязка к сетке</span><button id="snap" class="switch ${map.settings.snapToGrid?'on':''}"><span></span></button></div><label class="field">Фон<input id="background" type="color" value="${map.settings.background}"></label><button id="fitMap" class="secondary wide">⤢ Показать карту целиком</button></section>`
  $('#gridType').value=map.settings.gridType
  $$('.layer').forEach(row=>{row.onclick=e=>{if(e.target.closest('button,input'))return;map.activeLayerId=row.dataset.id;renderRightPanel(editor,map)};const input=row.querySelector('input');input.oninput=()=>{map.layers.find(l=>l.id===row.dataset.id).name=input.value;editor.scheduleSave()};row.querySelector('.vis').onclick=()=>{const l=map.layers.find(x=>x.id===row.dataset.id);l.visible=!l.visible;editor.selectedId=null;editor.scheduleSave();renderRightPanel(editor,map);editor.render()};row.querySelector('.lock').onclick=()=>{const l=map.layers.find(x=>x.id===row.dataset.id);l.locked=!l.locked;editor.selectedId=null;editor.scheduleSave();renderRightPanel(editor,map);editor.render()};row.querySelector('.del-layer').onclick=()=>{if(map.layers.length<=1)return;const fallback=map.layers.find(x=>x.id!==row.dataset.id);map.objects.filter(o=>o.layerId===row.dataset.id).forEach(o=>o.layerId=fallback.id);map.layers=map.layers.filter(x=>x.id!==row.dataset.id);if(map.activeLayerId===row.dataset.id)map.activeLayerId=fallback.id;editor.commit();renderRightPanel(editor,map)}})
  $('#addLayer').onclick=()=>{const l={id:uid('layer'),name:'Новый слой',visible:true,locked:false};map.layers.unshift(l);map.activeLayerId=l.id;editor.scheduleSave();renderRightPanel(editor,map)}
  const numeric=(id,key,min,max)=>{$(id).onchange=e=>{map.settings[key]=clamp(parseInt(e.target.value)||min,min,max);editor.scheduleSave();editor.render()}};numeric('#cols','columns',4,200);numeric('#rows','rows',4,200);numeric('#cellSize','cellSize',20,120)
  $('#gridType').onchange=e=>{map.settings.gridType=e.target.value;editor.scheduleSave();editor.render()};$('#gridVisible').onclick=()=>{map.settings.gridVisible=!map.settings.gridVisible;editor.scheduleSave();renderRightPanel(editor,map);editor.render()};$('#snap').onclick=()=>{map.settings.snapToGrid=!map.settings.snapToGrid;editor.scheduleSave();renderRightPanel(editor,map)};$('#background').oninput=e=>{map.settings.background=e.target.value;editor.scheduleSave();editor.render()};$('#fitMap').onclick=()=>editor.fit()
}
function layerRow(l,active){return `<div class="layer ${l.id===active?'active':''}" data-id="${l.id}"><button class="mini-btn vis" title="Показать/скрыть">${l.visible?'◉':'○'}</button><input value="${esc(l.name)}"><button class="mini-btn lock" title="Блокировка">${l.locked?'▣':'▢'}</button><button class="mini-btn danger del-layer" ${''} title="Удалить">✕</button></div>`}

