// Tirandor Cartographer v0.3 — curves, areas, legends, DM/player views
const TC_V03=(()=>{
  const ui={areaKind:'land',profile:'dm'}
  const AREAS={
    land:{label:'Земля / берег',fill:'rgba(161,132,78,.22)',stroke:'#6f5735'},water:{label:'Вода',fill:'rgba(78,126,151,.28)',stroke:'#537f97'},forest:{label:'Лесной массив',fill:'rgba(73,103,65,.24)',stroke:'#536b49'},swamp:{label:'Болото',fill:'rgba(80,103,82,.22)',stroke:'#596b5b'},desert:{label:'Пустошь',fill:'rgba(181,145,84,.24)',stroke:'#9c7b45'},realm:{label:'Граница владения',fill:'rgba(147,75,65,.10)',stroke:'#8b4f47'}
  }
  const extra=[['market','Рынок','landmarks','⚖'],['tavern','Таверна','landmarks','♨'],['manor','Поместье','settlements','⌂'],['guildhall','Гильдия','settlements','⚒'],['cemetery','Кладбище','sacred','†'],['watchtower','Дозорная башня','strongholds','♜'],['battlefield','Поле боя','landmarks','⚔'],['ferry','Переправа','landmarks','≈'],['orchard','Сады','terrain','❦'],['swamp','Болото','terrain','≋']]
  for(const [id,label,group,icon] of extra)if(!TC_V02.S.some(s=>s.id===id))TC_V02.S.push({id,label,group,icon})
  const areaStyle=id=>AREAS[id]||AREAS.land
  function pathBounds(points){const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs)||1,h:Math.max(...ys)-Math.min(...ys)||1}}
  function smooth(ctx,pts){if(!pts.length)return;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);if(pts.length===2){ctx.lineTo(pts[1].x,pts[1].y);return}for(let i=1;i<pts.length-1;i++){const m={x:(pts[i].x+pts[i+1].x)/2,y:(pts[i].y+pts[i+1].y)/2};ctx.quadraticCurveTo(pts[i].x,pts[i].y,m.x,m.y)}ctx.lineTo(pts[pts.length-1].x,pts[pts.length-1].y)}
  function pointDist(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,l=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((p.x-a.x)*vx+(p.y-a.y)*vy)/l)),x=a.x+t*vx,y=a.y+t*vy;return Math.hypot(p.x-x,p.y-y)}
  function drawPath(ctx,o,map){ctx.save();ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle=o.stroke||(o.pathKind==='river'?'#537f97':'#8a6d4a');ctx.lineWidth=o.width||(o.pathKind==='river'?12:9);if(o.pathKind==='road')ctx.setLineDash(o.roadStyle==='royal'?[2,0]:o.roadStyle==='trail'?[5,8]:[16,9]);smooth(ctx,o.points);ctx.stroke();if(o.pathKind==='river'){ctx.globalAlpha=.35;ctx.strokeStyle='#d7e3df';ctx.lineWidth=Math.max(2,(o.width||12)*.22);smooth(ctx,o.points);ctx.stroke()}ctx.restore()}
  function drawArea(ctx,o){const s=areaStyle(o.areaKind);ctx.save();ctx.fillStyle=o.fill||s.fill;ctx.strokeStyle=o.stroke||s.stroke;ctx.lineWidth=o.width||2;ctx.beginPath();o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();if(o.areaKind==='realm')ctx.setLineDash([12,8]);ctx.stroke();ctx.restore()}
  function legendItems(map){const ids=[...new Set(map.objects.filter(o=>o.type==='symbol').map(o=>o.symbol))].slice(0,10);return ids.map(id=>({id,label:TC_V02.def(id).label,icon:TC_V02.def(id).icon}))}
  function drawLegend(ctx,o,map){const items=o.items?.length?o.items:legendItems(map),row=24,w=o.w||190,h=42+items.length*row;ctx.save();ctx.fillStyle='rgba(239,226,199,.92)';ctx.strokeStyle=map.settings.ink||'#34291f';ctx.lineWidth=2;ctx.fillRect(o.x,o.y,w,h);ctx.strokeRect(o.x,o.y,w,h);ctx.fillStyle=map.settings.ink||'#34291f';ctx.font='700 18px Georgia';ctx.fillText(o.title||'Легенда',o.x+12,o.y+24);ctx.font='14px Georgia';items.forEach((it,i)=>{ctx.fillText(it.icon,o.x+14,o.y+48+i*row);ctx.fillText(it.label,o.x+42,o.y+48+i*row)});ctx.restore();o.w=w;o.h=h}
  function visible(map,id,base){if(!base)return false;const l=map.layers.find(x=>x.id===id),p=TC_V03.profile;if(p==='player'&&l?.audience==='gm')return false;return true}
  function addLegend(map,ed){const items=legendItems(map);if(!items.length)return toast('На карте пока нет символов для легенды');const o={id:uid('obj'),type:'legend',x:map.settings.cellSize,y:map.settings.cellSize,w:190,h:42+items.length*24,title:'Легенда',items,layerId:map.activeLayerId};map.objects.push(o);ed.selectedId=o.id;ed.commit();renderRightPanel(ed,map)}
  return{ui,AREAS,areaStyle,pathBounds,smooth,pointDist,drawPath,drawArea,legendItems,drawLegend,visible,addLegend,profile:'dm'}
})()

TOOL_LABELS.area=['⬠','Область'];TOOL_KINDS.area=['world','region','city','battle']
const tc3Visible=visibleLayer;visibleLayer=function(map,id){return TC_V03.visible(map,id,tc3Visible(map,id))}
const tc3Bounds=bounds;bounds=function(o){if(['path','area'].includes(o.type))return TC_V03.pathBounds(o.points);if(o.type==='legend')return{x:o.x,y:o.y,w:o.w||190,h:o.h||100};return tc3Bounds(o)}
const tc3Render=renderObject;renderObject=function(ctx,o,selected=false){const map=state.editor?.map||{settings:{ink:'#34291f'}};if(o.type==='path'){TC_V03.drawPath(ctx,o,map);if(selected)drawSelection(ctx,o);return}if(o.type==='area'){TC_V03.drawArea(ctx,o);if(selected)drawSelection(ctx,o);return}if(o.type==='legend'){TC_V03.drawLegend(ctx,o,map);if(selected)drawSelection(ctx,o);return}return tc3Render(ctx,o,selected)}
const tc3Hit=MapEditor.prototype.hitObject;MapEditor.prototype.hitObject=function(o,p){if(o.type==='path'){for(let i=1;i<o.points.length;i++)if(TC_V03.pointDist(p,o.points[i-1],o.points[i])<14/Math.max(this.zoom,.3))return true;return false}if(o.type==='area'){let c=false;for(let i=0,j=o.points.length-1;i<o.points.length;j=i++){const a=o.points[i],b=o.points[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||.0001)+a.x))c=!c}return c}return tc3Hit.call(this,o,p)}
const tc3Down=MapEditor.prototype.down,tc3Move=MapEditor.prototype.move,tc3Up=MapEditor.prototype.up,tc3Dup=MapEditor.prototype.duplicate
MapEditor.prototype.down=function(e){
  if(['road','river'].includes(this.tool)){const p=this.snap(this.world(e)),l=this.map.layers.find(x=>x.id===this.map.activeLayerId);if(l?.locked||!l?.visible)return toast('Активный слой скрыт или заблокирован');const o={id:uid('obj'),type:'path',pathKind:this.tool,roadStyle:'road',points:[p],stroke:this.tool==='river'?'#537f97':'#8a6d4a',width:this.tool==='river'?12:9,layerId:this.map.activeLayerId};this.map.objects.push(o);this.draft=o;this.mode='tc3path';this.tc3last=p;this.selectedId=o.id;this.render();return}
  if(this.tool==='area'){const p=this.snap(this.world(e)),s=TC_V03.areaStyle(TC_V03.ui.areaKind),o={id:uid('obj'),type:'area',areaKind:TC_V03.ui.areaKind,points:[p],fill:s.fill,stroke:s.stroke,width:2,layerId:this.map.activeLayerId};this.map.objects.push(o);this.draft=o;this.mode='tc3area';this.tc3last=p;this.selectedId=o.id;this.render();return}
  tc3Down.call(this,e)
}
MapEditor.prototype.move=function(e){const raw=this.world(e),p=this.snap(raw);if(['tc3path','tc3area'].includes(this.mode)&&this.draft){if(Math.hypot(p.x-this.tc3last.x,p.y-this.tc3last.y)>Math.max(4,8/this.zoom)){this.draft.points.push(p);this.tc3last=p;this.render()}return}const o=this.selected();if(o&&['path','area'].includes(o.type)&&this.mode==='drag'&&this.start){const dx=raw.x-this.start.x,dy=raw.y-this.start.y;o.points=this.start.base.points.map(q=>({x:q.x+dx,y:q.y+dy}));this.render();return}tc3Move.call(this,e)}
MapEditor.prototype.up=function(e){if(this.mode==='tc3path'){if(this.draft.points.length<2)this.map.objects=this.map.objects.filter(o=>o!==this.draft);this.commit();this.mode=null;this.draft=null;return}if(this.mode==='tc3area'){if(this.draft.points.length<3)this.map.objects=this.map.objects.filter(o=>o!==this.draft);this.commit();this.mode=null;this.draft=null;return}tc3Up.call(this,e)}
MapEditor.prototype.duplicate=function(){const o=this.selected();if(o&&['path','area'].includes(o.type)){const c=deep(o);c.id=uid('obj');c.points=c.points.map(p=>({x:p.x+20,y:p.y+20}));this.map.objects.push(c);this.selectedId=c.id;this.commit();return}if(o?.type==='legend'){const c=deep(o);c.id=uid('obj');c.x+=20;c.y+=20;this.map.objects.push(c);this.selectedId=c.id;this.commit();return}tc3Dup.call(this)}

const tc3Grid=drawGrid;drawGrid=function(ctx,map){tc3Grid(ctx,map);if(!map.settings.coordsVisible||!map.settings.gridVisible)return;const c=map.settings.cellSize,w=map.settings.columns*c,h=map.settings.rows*c;ctx.save();ctx.fillStyle=map.settings.ink||'#34291f';ctx.globalAlpha=.55;ctx.font=`${Math.max(9,c*.18)}px Georgia`;ctx.textAlign='center';for(let x=0;x<map.settings.columns;x++)ctx.fillText(String.fromCharCode(65+(x%26)),x*c+c/2,Math.max(10,c*.2));ctx.textAlign='left';for(let y=0;y<map.settings.rows;y++)ctx.fillText(String(y+1),4,y*c+c*.55);ctx.restore()}

const tc3Right=renderRightPanel;renderRightPanel=function(ed,map){map.settings.coordsVisible??=false;map.layers.forEach(l=>{l.audience||='both';if(/^GM\b/i.test(l.name)&&l.audience==='both')l.audience='gm'});tc3Right(ed,map);const rp=$('#rightPanel');if(!rp)return;const p=document.createElement('section');p.className='panel tc3-panel';p.innerHTML=`<span class="eyebrow">v0.3 Cartography</span><h3>Кривые и области</h3><label class="field">Тип области<select id="tc3Area">${Object.entries(TC_V03.AREAS).map(([id,a])=>`<option value="${id}" ${TC_V03.ui.areaKind===id?'selected':''}>${a.label}</option>`).join('')}</select></label><div class="tc3-actions"><button id="tc3AreaTool" class="secondary">⬠ Рисовать область</button><button id="tc3Legend" class="secondary">☷ Автолегенда</button></div><div class="toggle"><span>Координаты сетки</span><button id="tc3Coords" class="switch ${map.settings.coordsVisible?'on':''}"><span></span></button></div><p class="muted">Дороги и реки теперь рисуются свободной кривой. Области подходят для берегов, лесов, болот, пустошей и границ владений.</p>`;rp.insertBefore(p,rp.children[1]||rp.firstChild);$('#tc3Area').onchange=e=>TC_V03.ui.areaKind=e.target.value;$('#tc3AreaTool').onclick=()=>{ed.setTool('area');$$('.tool').forEach(t=>t.classList.toggle('active',t.dataset.tool==='area'))};$('#tc3Legend').onclick=()=>TC_V03.addLegend(map,ed);$('#tc3Coords').onclick=()=>{map.settings.coordsVisible=!map.settings.coordsVisible;ed.scheduleSave();ed.render();renderRightPanel(ed,map)}
  $$('.layer').forEach(row=>{const l=map.layers.find(x=>x.id===row.dataset.id);if(!l||row.querySelector('.tc3-aud'))return;const b=document.createElement('button');b.className='mini-btn tc3-aud';b.title='Видимость при экспорте: both / player / GM';b.textContent=l.audience==='gm'?'G':l.audience==='player'?'P':'◎';row.appendChild(b);b.onclick=e=>{e.stopPropagation();l.audience=l.audience==='both'?'player':l.audience==='player'?'gm':'both';ed.scheduleSave();renderRightPanel(ed,map)}})
  const o=ed.selected?.();if(o&&['path','area','legend'].includes(o.type)){const i=document.createElement('section');i.className='panel tc3-inspector';if(o.type==='path')i.innerHTML=`<span class="eyebrow">Path</span><h3>${o.pathKind==='river'?'Река':'Дорога'}</h3><div class="field-grid two"><label>Толщина<input id="tc3Width" type="number" min="1" max="50" value="${o.width||8}"></label><label>Стиль<select id="tc3Road"><option value="trail">Тропа</option><option value="road">Дорога</option><option value="royal">Королевский тракт</option></select></label></div>`;else if(o.type==='area')i.innerHTML=`<span class="eyebrow">Area</span><h3>Область</h3><label class="field">Тип<select id="tc3AreaObj">${Object.entries(TC_V03.AREAS).map(([id,a])=>`<option value="${id}" ${o.areaKind===id?'selected':''}>${a.label}</option>`).join('')}</select></label>`;else i.innerHTML=`<span class="eyebrow">Legend</span><h3>Легенда</h3><label class="field">Заголовок<input id="tc3Title" value="${esc(o.title||'Легенда')}"></label><button id="tc3Refresh" class="secondary wide">Обновить по символам карты</button>`;rp.insertBefore(i,p.nextSibling);const w=i.querySelector('#tc3Width');if(w)w.onchange=()=>{o.width=+w.value;ed.commit()};const r=i.querySelector('#tc3Road');if(r){r.value=o.roadStyle||'road';r.onchange=()=>{o.roadStyle=r.value;ed.commit()}}const a=i.querySelector('#tc3AreaObj');if(a)a.onchange=()=>{o.areaKind=a.value;const s=TC_V03.areaStyle(a.value);o.fill=s.fill;o.stroke=s.stroke;ed.commit();renderRightPanel(ed,map)};const t=i.querySelector('#tc3Title');if(t)t.onchange=()=>{o.title=t.value;ed.commit()};const rf=i.querySelector('#tc3Refresh');if(rf)rf.onclick=()=>{o.items=TC_V03.legendItems(map);ed.commit()}}
}

const tc3Export=exportMapModal;exportMapModal=function(ed,map){showModal(`<div class="modal"><div class="modal-title"><div><span class="eyebrow">Экспорт v0.3</span><h2>${esc(map.name)}</h2></div><button class="icon-btn modal-close">✕</button></div><label class="field">Профиль<select id="tc3Profile"><option value="dm">DM — все слои</option><option value="player">Player — скрыть GM-only</option></select></label><button id="tc3Png" class="export-card"><b style="font-size:24px">▧</b><div><strong>PNG x2</strong><span>С учётом выбранного профиля слоёв</span></div></button><div class="segmented"><button class="print-mode active" data-mode="fit">На один лист</button><button class="print-mode" data-mode="battle">Battlemap 1″</button></div><div class="field-grid two"><label>Бумага<select id="paper"><option value="a4">A4</option><option value="a3">A3</option></select></label><label>Ориентация<select id="orient"><option value="landscape">Альбомная</option><option value="portrait">Книжная</option></select></label></div><button id="tc3Print" class="primary wide">⎙ Печать / PDF</button></div>`);let mode='fit';$$('.print-mode').forEach(b=>b.onclick=()=>{$$('.print-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});$('#tc3Png').onclick=()=>{const old=TC_V03.profile;TC_V03.profile=$('#tc3Profile').value;const c=renderMapToCanvas(map,2,false);TC_V03.profile=old;c.toBlob(b=>b&&downloadBlob(b,`${safe(map.name)}-${$('#tc3Profile').value}.png`),'image/png')};$('#tc3Print').onclick=()=>{TC_V03.profile=$('#tc3Profile').value;printMap(map,mode,$('#paper').value,$('#orient').value);setTimeout(()=>TC_V03.profile='dm',100)}}
